// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace tokero_DCA_calculator.Models;

public partial class CryptoValue: MonthlyCryptoPrice
{
    public int Id { get; set; }
    public string Name { get; set; }
}