// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;

namespace tokero_DCA_calculator.Models;

public partial class CryptoContext : DbContext
{
    public CryptoContext(DbContextOptions<CryptoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CryptoValue> CryptoValues { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CryptoValue>(entity =>
        {
            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}