// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;

namespace tokero_DCA_calculator.Models;

public partial class CryptoContext : DbContext
{
    public CryptoContext(DbContextOptions<CryptoContext> options)
        : base(options)
    {
    }
    public virtual DbSet<CryptoValue> Cryptocurrencies { get; set; }
    public virtual DbSet<InvestmentEntryMonths> InvestmentEntriesMonths{ get; set; }
    public virtual DbSet<InvestmentEntryHeader> InvestmentEntriesHeaders{ get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CryptoValue>(entity =>
        {
            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
        });
        modelBuilder.Entity<InvestmentEntryMonths>()
                    .Property(e => e.CryptoAmount)
                    .HasColumnType("DECIMAL(20, 20)");

        OnModelCreatingPartial(modelBuilder);
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        optionsBuilder.ConfigureWarnings(warnings => warnings.Ignore(RelationalEventId.PendingModelChangesWarning));
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}